from __future__ import annotations

import json

from deplens.prediction.baselines import Prediction


def risk_score(predictions: list[Prediction]) -> float:
    if not predictions:
        return 0.0
    return 100.0 * sum(p.score for p in predictions) / len(predictions)


def risk_band(score: float) -> str:
    if score < 34.0:
        return "low"
    if score < 67.0:
        return "medium"
    return "high"


def to_json(data: dict) -> str:
    return json.dumps(data, indent=2, sort_keys=True)


def predictions_markdown(predictions: list[Prediction]) -> str:
    score = risk_score(predictions)
    lines = [f"Risk score: {score:.0f}/100 ({risk_band(score)})", "", "| Rule | Verdict |", "| --- | --- |"]
    for prediction in predictions:
        verdict = "risky" if prediction.label else "clear"
        lines.append(f"| {prediction.rule} | {verdict} |")
    return "\n".join(lines)


def analysis_markdown(analysis: dict) -> str:
    deps = analysis["dependencies"]
    imports = analysis["imports"]
    usage = analysis["usage"]
    lines = [
        f"# DepLens report: {analysis['root']}",
        "",
        "## Dependencies",
        "",
        f"Files: {', '.join(analysis['dependency_files']) or 'none found'}",
        f"Packages: {len(deps['nodes'])} ({len(deps['edges'].get(deps['root'], []))} direct)",
        "",
        "## Code usage",
        "",
        f"Imports: {imports['count']} ({imports['linked']} linked, "
        f"{imports['stdlib']} stdlib, {imports['unresolved']} unresolved)",
        f"Distinct APIs used: {len(usage['qualified'])}",
        "",
    ]
    if analysis["parse_errors"]:
        lines += ["## Parse errors", ""]
        lines += [f"- {error}" for error in analysis["parse_errors"]] + [""]
    lines += ["_Generated by DepLens. Scores are unevaluated heuristics, not predictions._"]
    return "\n".join(lines)
